### ISSUE TITLE
不能同时处理

### ISSUE THREAD

**Issue by einsqing** [Bryght7/parallel-minterpolate#1]
ffmpeg -i "C:\Users\heqing\Desktop\git\human-infer\temp\090905.mp4" -c copy -map 0 -segment_time 0:00:04 -f segment -reset_timestamps 1 output%%03d.mp4
(
  start "TASK 1" ffmpeg -i output000.mp4 -crf 10 -vf "minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" output000.30fps.mp4
  start "TASK 2" ffmpeg -i output001.mp4 -crf 10 -vf "minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" output001.30fps.mp4
  start "TASK 3" ffmpeg -i output002.mp4 -crf 10 -vf "minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" output002.30fps.mp4
  start "TASK 4" ffmpeg -i output003.mp4 -crf 10 -vf "minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" output003.30fps.mp4
  start "TASK 5" ffmpeg -i output004.mp4 -crf 10 -vf "minterpolate=fps=30:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" output004.30fps.mp4
) | pause
timeout /t 3 /nobreak > nul
ffmpeg -f concat -safe 0 -i list.txt -c copy final.mp4

output002.mp4正常处理，其他跟卡住了一样，处理的极慢

**Comment by Bryght7** [comment]
Hello,

If your video is 20 seconds long, I think maybe it's too short to split it in 5 tasks.

Maybe try with 2 tasks with option `--split 2`
